services:
  mysql_db:
    platform: linux/amd64
    image: ${ECR_PULL_THROUGH_REPOSITORY_URL}library/mysql:8.0.20
    volumes:
      - ./conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: test_ci
    networks:
      - dbnet
    ports:
      - "3306:3306"

networks:
  dbnet:
    driver: bridge
