services:
  server:
    image: ${ECR_PULL_THROUGH_REPOSITORY_URL}library/yandex/clickhouse-server
    ports:
      - "9000:9000"

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
